version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: django_app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: django_app-admin
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
       - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      -  .:/code
    ports:
      - "8000:8000"
    depends_on:
      -  db
volumes:
  mysql-data:
